### ISSUE TITLE
Support `# fmt: skip`, `# yapf: disable`

### ISSUE THREAD

**Issue by JelleZijlstra** [Pierre-Sassoulas/black-disable-checker#4]
In addition to `# fmt: off`, Black supports skipping formatting in a few more ways. See https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html?highlight=fmt#code-style.

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the issue, I missed that. It should work in ``1.1.0``.
